# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0003_auto_20160424_2129"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="thumbnail",
            field=models.URLField(blank=True, null=True),
        ),
    ]
