# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-24 21:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_bookmark_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='image',
        ),
    ]
