# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-26 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0006_auto_20160425_2306"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
