# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-28 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0007_auto_20160426_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
