# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-30 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0009_auto_20160507_1837"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="thumbnail",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
