# Generated by Django 3.0.7 on 2020-07-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookmark", "0010_auto_20171130_1840"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name="folder",
            name="is_deleted",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
